### ISSUE TITLE
MotorA and B naming

### ISSUE THREAD

**Issue by bforce33** [JP-Vela/EnchantedTreasureChest#1]
Your code is really good and clean so this is just a really nitpicky thing but the two MotorsA and MotorB could be renamed. In the beginning, I was confused as to why there were two different motors but then after reading the code I realized one motor opens the chest and the other closes it. To help with clarity in what their purposes are and to perhaps prevent mixing them up in the future if you were to add more to the code, I would consider naming them something along the lines of openingMotor and closingMotor. Also, in the opening and closing lid function, you seem to be writing the non-used motor to low twice in the function. I don't think you need this repeated code.

**Comment by JP-Vela** [comment]
Sorry about the confusion with the naming. The motor used utilizes 2 digital pins to move forward and backwards so I will make the names clearer as well as add in some more comments.
Thank you for pointing out I am setting one of the pins LOW twice in the same function, I will also remove that unnecessary part.
