### ISSUE TITLE
RFID code confsuion

### ISSUE THREAD

**Issue by bforce33** [JP-Vela/EnchantedTreasureChest#2]
This very well may not be needed, but I would say the most confusing part of the code is understanding how the Chest reads the RFID card. The rest of the code (because of your clean layout and great variable names) are easy enough to understand for anyone who has worked with arduinos. But as someone who had never coded with an RFID card I could only guess at how things were working. Perhaps an extra comment or two about how the Code is handling reading the RFID number could help new programmers work on this code in the future.

**Comment by JP-Vela** [comment]
Thank you for the suggestion! I will add in some more comments and elaborate on which parts read from the sensor.
